name: flutterapk

on: 
  push:
    branches:

permissions: write-all

jobs:
     
  myrelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - run: flutter doctor