name: flutterapk

on: 
  push:
    branches:

permissions: write-all
jobs:
  myrelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'
      - name: Create and build
        run: |
          flutter pub get
          flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/apk/debug/app-debug.apk